openapi: "3.0.0"
info:
  title: "User Email Registration API"
  description: "このAPIは、スプレッドシート内のメールをチェックし、登録されていなければ登録するためのものです。"
  version: "1.0.0"
servers:
  - url: "https://script.google.com"
paths:
  /macros/s/XXXXXXXXXXXXXXXXX/exec:
    post:
      summary: "ユーザー登録または認証"
      description: "新規登録または認証を行います。"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: "ユーザーのメールアドレス"
                password:
                  type: string
                  description: "認証用のパスワード（新規登録時は省略可能）"
              required:
                - email
      responses:
        "200":
          description: "登録または認証が成功した場合"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                      - denied
                      - error
                  message:
                    type: string
        "400":
          description: "不正なリクエスト"
        "500":
          description: "サーバ内部エラー"
